### ISSUE TITLE
Medals

### ISSUE THREAD

**Issue by davidhouweling** [GravlLift/halo-infinite-api#5]
Not necessarily an issue but I wanted to know how medals are being handled in your application when using the API?

Looking at https://den.dev/blog/halo-infinite-medal-api-update/ and from my own digging into the network calls for Halowaypoint API responses, the https://gamecms-hacs.svc.halowaypoint.com/hi/Waypoint/file/medals/metadata.json response contains all the mapping from the `Medals.NameId` to actual name + description.

I could hard code this on my end but i was wondering if we could update the client to be able to pull the medals/metadata.json file which can then be used to map between the two?

**Comment by GravlLift** [comment]
My particular use case, haloquery.com, doesn't do anything with medals, with the sole exception of counting perfects (NameId `1512363953` if you're curious). No sprite usage or anything like that, so that particular endpoint hasn't been something I've needed.

If you're interested in adding that to the client, I'd certainly welcome a pull request though. There's something similar to it in the halo-infinite-client.ts file, except its for Progression instead of Waypoint:

https://github.com/GravlLift/halo-infinite-api/blob/37718d09251c9806afe558bb6645f9d14f147eb1/src/core/halo-infinite-client.ts#L385-L395

I haven't looked too hard at this, so I'm not sure if this is better served as a new method that looks similar to `getProgressionFile`, or if it'd be better to replace it with something more generic like a `getFile`.

Take a look if you're interested though.

**Comment by GravlLift** [comment]
Released in [9.2.0](https://github.com/GravlLift/halo-infinite-api/releases/tag/9.2.0)
